-- Baseline: the schema as it existed under hibernate.ddl-auto=update (ADR-001 Conversation/
-- Message, ADR-007 users) before Flyway was introduced (see docs/decision/008). Existing
-- databases are onboarded via spring.flyway.baseline-on-migrate/baseline-version in
-- application.yaml, so this file never actually runs against them — it only executes for real
-- against a brand-new, empty database (fresh dev setup, CI). Never edit this file once it has
-- shipped; every schema change from here on is a new Vn__*.sql.

CREATE TABLE conversations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       VARCHAR(255)  NOT NULL UNIQUE,
    owner_id   BIGINT,
    created_at TIMESTAMP(6)  NOT NULL
);

CREATE TABLE messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT REFERENCES conversations (id),
    role            VARCHAR(255) NOT NULL CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM')),
    content         TEXT         NOT NULL,
    created_at      TIMESTAMP(6)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL
);
