-- V3__create_document_table.sql (Flyway migration)
-- Backs DocumentJpaEntity (org.timpeng.chatbot.rag.document). V2 only created document_chunk;
-- nothing before this created the parent `document` row that DocumentController/DocumentService
-- persist on upload. document_chunk gaining a document_id FK to this table is a separate,
-- follow-up migration (tracked with the rest of the split -> embed -> vector-store pipeline —
-- see DocumentService's TODO).
CREATE TABLE document
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid         VARCHAR(255) NOT NULL UNIQUE,
    title        VARCHAR(255) NOT NULL,
    content      TEXT         NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    uploaded_at  TIMESTAMP(6) NOT NULL,
    total_chunks INT          NOT NULL DEFAULT 0,
    user_id      BIGINT       NOT NULL REFERENCES users (id)
);

CREATE INDEX idx_document_user_id ON document (user_id);
